name: Deploy to Wasmer Edge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Wasmer
        run: curl https://get.wasmer.io -sSfL | sh

      - name: Add Wasmer to PATH
        run: echo "$HOME/.wasmer/bin" >> $GITHUB_PATH

      - name: Check deploy flags
        run: wasmer deploy --help

      - name: Deploy to Wasmer Edge
        run: wasmer deploy --non-interactive --token ${{ secrets.WASMER_TOKEN }}
